package by.epam.totalizator.controller;

public final class RequestParameterName {
	
	public static final String ACCESS_DENIED = "accessDenied";
	public static final String ADMIN = "admin";
	public static final String ALLOW_BET = "allowBet";
	public static final String BALANCE = "balance";
	public static final String BET_LIST = "betList";
	public static final String CHANGED_LANGUAGE = "changedLanguage";
	public static final String COMMAND = "command";
	public static final String COMPETITION = "competition";
	public static final String COMPETITION_ID = "competitionId";
	public static final String CONCURENSE_LOGIN = "concurenseLogin";
	public static final String CURRENT_COMMAND = "currentCommand";
	public static final String CURRENT_PAGE = "currentPage";
	public static final String ERROR_MESSAGE = "errorMessage";
	public static final String EVENT_DATE = "eventDate";
	public static final String EVENT_DRAW_COEFF = "eventDrawCoeff";
	public static final String EVENT_LOSE_COEFF = "eventLoseCoeff";
	public static final String EVENT_MIN_BET = "eventMinBet";
	public static final String EVENT_MAX_BET = "eventMaxBet";
	public static final String EVENT_NAME = "eventName";
	public static final String EVENT_WIN_COEFF = "eventWinCoeff";
	public static final String LINE = "line";
	public static final String LINE_ID = "lineId";
	public static final String LOCALE = "locale";
	public static final String LOGIN = "login";
	public static final String NAME = "name";
	public static final String OUTCOME = "outcome";
	public static final String PAGE_LIST = "pageList";
	public static final String PASSWORD = "password";
	public static final String REG_ADDRESS = "regAddress";
	public static final String REG_DATE_OF_BIRTH = "regBirthday";
	public static final String REG_EMAIL = "regEmail";
	public static final String REG_LOGIN = "regLogin";
	public static final String REG_NAME = "regName";
	public static final String REG_PASSPORT = "regPassport";
	public static final String REG_PASSWORD = "regPassword";
	public static final String REG_PHONE = "regPhone";
	public static final String REG_SURNAME = "regSurname";
	public static final String SEARCH_TEXT = "searchText";
	public static final String SCORE1 = "score1";
	public static final String SCORE2 = "score2";
	public static final String SPORT = "sport";
	public static final String SPORT_ID = "sportId";
	public static final String SUMMA = "summa";
	public static final String TOTAL_PAGE = "totalPage";
	public static final String UNRESOLVED_MONEY = "unresolvedMoney";
	public static final String USER = "client";
	public static final String USER_ID = "userId";
	public static final String USER_LIST = "userList";
}
