package by.epam.totalizator.command;

public enum CommandName {
	ADD_EVENT,
	ALLOW_BET,
	CHANGE_LOCALE,
	CONTACTS,
	FIX_RESULT,
	HOME,
	LOGIN,
	LOGOUT,
	MAKE_DEPOSIT,
	MAKE_BET,
	REGISTER_USER,
	REGISTRATION,
	REMOVE_USER,
	SHOW_BET_HISTORY,
	SHOW_DEPOSIT,
	SHOW_EVENT_CREATION,
	SHOW_LINE,
	SHOW_RESULT,
	SHOW_RESULT_FOR_FIX,
	SHOW_USER_LIST
}
