package by.epam.totalizator.command;

public enum CommandName {
	ALLOW_BET,
	CHANGE_LOCALE,
	CONTACTS,
	HOME,
	LOGIN,
	LOGOUT,
	MAKE_DEPOSIT,
	REGISTER_USER,
	REGISTRATION,
	REMOVE_USER,
	SHOW_BET_HISTORY,
	SHOW_DEPOSIT,
	SHOW_LINE,
	SHOW_RESULT,
	SHOW_USER_LIST
}
